---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    name: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  labels:
    name: backend
---
apiVersion: v1
kind: Namespace
metadata:
  name: payment
  labels:
    name: payment
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: frontend
  labels:
    component: frontend
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>Hey! I am the website frontend</h1>
    </body>
    </html>
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen 80;
        server_name localhost;

        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: backend
  labels:
    component: backend
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>Hey I am the backend server</h1>
    </body>
    </html>
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      sendfile        on;
      keepalive_timeout  65;

      server {
        listen 80;
        server_name localhost;

        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: payment
  labels:
    component: payment
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <body>
    <h1>Hey I am the payment API</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: frontend
  labels:
    app: nginx
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      component: frontend
  template:
    metadata:
      labels:
        app: nginx
        component: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-conf-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      - name: nginx-conf-volume
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
  labels:
    component: frontend
spec:
  selector:
    app: nginx
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: backend
  labels:
    app: nginx
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      component: backend
  template:
    metadata:
      labels:
        app: nginx
        component: backend
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
        - name: nginx-conf-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
      - name: nginx-conf-volume
        configMap:
          name: nginx-config
          items:
          - key: nginx.conf
            path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
  labels:
    component: backend
spec:
  selector:
    app: nginx
    component: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  namespace: payment
  labels:
    app: nginx
    component: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      component: payment
  template:
    metadata:
      labels:
        app: nginx
        component: payment
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: payment
  labels:
    component: payment
spec:
  selector:
    app: nginx
    component: payment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
